version: '3.8'
services:
  dev:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: portafolio-dev
    ports:
      - "5173:5173"
    volumes:
      - .:/app
      - /app/node_modules